import {Component, inject} from '@angular/core';
import {BreakpointObserver, Breakpoints} from "@angular/cdk/layout";
import {map, Observable, shareReplay} from "rxjs";
import Big from "big.js";
import {environment} from "../../../environments/environment.development";
import {Fixdepositaccount} from "../../models/fixdepositaccount";
import {HttpClient} from "@angular/common/http";

@Component({
  selector: 'app-fix-deposit-account-module',
  templateUrl: './fix-deposit-account-module.component.html',
  styleUrls: ['./fix-deposit-account-module.component.scss']
})
export class FixDepositAccountModuleComponent {
  private breakpointObserver = inject(BreakpointObserver);
  accountNumber: number = 0;
  maturityDate: Date = new Date();
  interestEarned: Big = new Big(0.00);

  depositAmount: Big = new Big(0.00);
  maturityDateIs:Date = new Date();
  interestRate: Big = new Big(0.00);
  accountId: number = 0;

  isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
    .pipe(
      map(result => result.matches),
      shareReplay());

  constructor(private http: HttpClient) {
  }


  onFormSubmit(event: any) {
    event.preventDefault();

    const javascriptDate = new Date();
    const year = javascriptDate.getFullYear();
    const month = String(javascriptDate.getMonth() + 1).padStart(2, "0"); // Months are 0-indexed, so we add 1
    const day = String(javascriptDate.getDate()).padStart(2, "0");
    const formattedDate = `${year}-${month}-${day}`;


    const fixDepositAccount = {
      depositAmount:this.depositAmount,
      createDate: formattedDate,
      maturityDate:this.maturityDateIs,
      interestRate:this.interestRate,
      accountId:this.accountId
    };

    this.http.post<Fixdepositaccount>(`${environment.apiUrl}/fixdepositaccount`, fixDepositAccount)
        .subscribe((response: any) => {
              // Success handling here
              alert(`Successfully created, and kindly remember this one-time autogenerated Fix Deposit Account ID for future interactions.your Fix Deposit account id is :${response}`);

            },
            (error) => {
              console.log(error);
            });
  }

  getFixDepositDetails(event: any) {
    event.preventDefault();

    this.http.get(`${environment.apiUrl}/fixdepositaccount/${this.accountNumber}`)
        .subscribe((response: any) => {
              if (response === null){
                alert('please insert correct account number');
              }
              this.maturityDate = response.maturityDate;
              this.interestEarned = response.interestEarned !== null ? new Big(response.interestEarned) : new Big(0);
            },
            (error) => {
              console.log(error);
            });

  }
}
