import {Component, inject} from '@angular/core';
import {BreakpointObserver, Breakpoints} from "@angular/cdk/layout";
import {map, Observable, shareReplay} from "rxjs";
import {environment} from "../../../environments/environment.development";
import {HttpClient} from "@angular/common/http";
import {LoanAccount} from "../../models/loanaccount";


@Component({
  selector: 'app-loan-account-module',
  templateUrl: './loan-account-module.component.html',
  styleUrls: ['./loan-account-module.component.scss']
})
export class LoanAccountModuleComponent {

  private breakpointObserver = inject(BreakpointObserver);
  accountNumber: any;
  amount: any;
  loanAmount: any;
  createDate: any;
  interestRate: any;
  accountId: any;



  isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
    .pipe(
      map(result => result.matches),
      shareReplay());

  constructor(private http: HttpClient) {
  }

  onFormSubmit(event: any) {
    event.preventDefault();

    const loanAccount = {

      loanAmount:this.loanAmount,
      createDate: this.createDate,
      interestRate:this.interestRate,
      accountId:this.accountId

    };

    this.http.post<LoanAccount>(`${environment.apiUrl}/loanaccount`, loanAccount)
      .subscribe((response: any) => {

          alert(`Successfully created, and kindly remember this one-time autogenerated Loan Account ID for future interactions.your Loan account id is :${response}`);

        },
        (error) => {
          console.log(error);
        });
  }

  updateLoan(event: any) {
    event.preventDefault();

    this.http.patch(`${environment.apiUrl}/loanaccount/loanrepay/${this.accountNumber}`,this.amount).subscribe((response:any)=>{

      alert('successfully updated');
    },
      (error) => {
        console.log(error);
      });

  }
}
