import {Component, inject} from '@angular/core';
import {BreakpointObserver, Breakpoints} from "@angular/cdk/layout";
import {map, Observable, shareReplay} from "rxjs";
import {HttpClient} from "@angular/common/http";
import {LoanAccount} from "../../models/loanaccount";
import {environment} from "../../../environments/environment.development";
import {Savingaccount} from "../../models/savingsaccount";

@Component({
  selector: 'app-savings-account-module',
  templateUrl: './savings-account-module.component.html',
  styleUrls: ['./savings-account-module.component.scss']
})
export class SavingsAccountModuleComponent {
  private breakpointObserver = inject(BreakpointObserver);
  interestRate: any;
  withdrawalLimit: any;
  accountId: any;

  isHandset$: Observable<boolean> = this.breakpointObserver.observe(Breakpoints.Handset)
    .pipe(
      map(result => result.matches),
      shareReplay());

  constructor(private http: HttpClient) {
  }

  onFormSubmit(event: any) {
    event.preventDefault();

    const javascriptDate = new Date();
    const year = javascriptDate.getFullYear();
    const month = String(javascriptDate.getMonth() + 1).padStart(2, "0"); // Months are 0-indexed, so we add 1
    const day = String(javascriptDate.getDate()).padStart(2, "0");
    const formattedDate = `${year}-${month}-${day}`;

    const savingsAccount = {
      createDate:formattedDate,
      interestRate: this.interestRate,
      withdrawalLimit:this.withdrawalLimit,
      accountId:this.accountId

    };

    this.http.post<Savingaccount>(`${environment.apiUrl}/savingaccount`, savingsAccount)
      .subscribe((response: any) => {

          alert(`Successfully created, and kindly remember this one-time autogenerated Savings Account ID for future interactions.your Savings account id is :${response}`);

        },
        (error) => {
          console.log(error);
        });

  }
}
